### ISSUE TITLE
Last run failed 2 months ago with status code 255. 

### ISSUE THREAD

**Issue by hanecak** [soit-sk/vyberove_konania_ms_sr#1]
Scraper konci s chybou a nezbiera ziadne udaje:

```
Last run failed 2 months ago with status code 255.
```

Nejake udaje su vytazene, ale nove nepribudaju.

**Comment by hanecak** [comment]
Stav k 11.201.2015: Lubo pocas Scraper Challenge hlasil, ze uz by to malo byt opravene. Scraper na Morph.io aktualne bezi, zrejme s reviziou e4da1bc .

Pockame teda, ako dobehne run na Morph.io .

**Comment by katkad** [comment]
Last run completed successfully about 8 hours ago. 

len ho treba spustat v noci; bezi 5 hodin, a v iny cas timeoutuje napriek roznym opatreniam
